export const ReduxLoadingConstants = {
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    SET_INTERNET_CONNECTION: 'SET_INTERNET_CONNECTION',
    SET_API_MESSAGE: 'SET_API_MESSAGE',
}